import { NextRequest, NextResponse } from 'next/server'
import { requireClientSession } from '@/lib/clientApiAuth'
import { createServerClient } from '@/lib/supabase'
import { sendReferralEmail } from '@/lib/emails'
import { sendSlackNotification } from '@/lib/slack'

// GET /api/client/referrals — list referrals sent by the logged-in client
export async function GET(req: NextRequest) {
  const auth = requireClientSession(req)
  if (auth.error) return auth.error
  const { session } = auth

  const supabase = createServerClient()
  const { data, error } = await supabase
    .from('referrals')
    .select('*')
    .eq('client_user_email', session.email)
    .order('sent_at', { ascending: false })

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json(data || [])
}

// POST /api/client/referrals — send a new referral
export async function POST(req: NextRequest) {
  const auth = requireClientSession(req)
  if (auth.error) return auth.error
  const { session } = auth

  const body = await req.json()
  const { referee_name, referee_email, referee_company, referee_need, referring_name, personal_note } = body

  if (!referee_name || !referee_email || !referee_company) {
    return NextResponse.json({ error: 'Referee name, email, and company are required' }, { status: 400 })
  }

  const supabase = createServerClient()

  // Get client company info for social proof block
  const { data: companyRow } = await supabase
    .from('client_companies')
    .select('id, name, created_at')
    .eq('id', session.company_id)
    .single()

  // Calculate "client since" duration
  let clientSinceDuration: string | undefined
  if (companyRow?.created_at) {
    const months = Math.round(
      (Date.now() - new Date(companyRow.created_at).getTime()) / (1000 * 60 * 60 * 24 * 30)
    )
    clientSinceDuration = months >= 12
      ? `${Math.floor(months / 12)} year${Math.floor(months / 12) > 1 ? 's' : ''}`
      : `${months} month${months !== 1 ? 's' : ''}`
  }

  // Auto-create referral record (referral_code generated by DB default)
  const { data: referral, error: refErr } = await supabase
    .from('referrals')
    .insert({
      client_user_email: session.email,
      client_company_id: session.company_id || null,
      client_company_name: session.company_name,
      referring_name: referring_name || session.company_name,
      referee_name,
      referee_email,
      referee_company,
      referee_need: referee_need || null,
      personal_note: personal_note || null,
    })
    .select()
    .single()

  if (refErr) return NextResponse.json({ error: refErr.message }, { status: 500 })

  // Auto-create prospect contact in CRM
  const { data: contact } = await supabase
    .from('contacts')
    .insert({
      name: referee_name,
      company: referee_company,
      email: referee_email,
      source: 'referral',
      referred_by: `${referring_name || session.company_name} (${session.email})`,
      status: 'prospect',
      notes: referee_need ? `Referred need: ${referee_need}` : null,
    })
    .select('id')
    .single()

  // Link contact_id to the referral
  if (contact?.id) {
    await supabase
      .from('referrals')
      .update({ contact_id: contact.id })
      .eq('id', referral.id)
  }

  // Send the referral email
  try {
    await sendReferralEmail({
      referee_name,
      referee_email,
      referee_company,
      referring_name: referring_name || session.company_name,
      referring_company: session.company_name,
      referring_company_since: clientSinceDuration,
      personal_note: personal_note || undefined,
      referral_code: referral.referral_code,
    })
  } catch (e) {
    console.error('[api/client/referrals] referral email failed:', e)
  }

  // Slack notification
  await sendSlackNotification(
    `🤝 Referral sent by *${referring_name || session.company_name}* @ ${session.company_name} → *${referee_name}* at *${referee_company}*`
  )

  return NextResponse.json({ ok: true, referral_code: referral.referral_code })
}
