import { NextRequest, NextResponse } from 'next/server'
import { createServerClient } from '@/lib/supabase'
import { getAuthUser, stripFinancials } from '@/lib/auth'

export async function GET(req: NextRequest) {
  const user = await getAuthUser(req)
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const supabase = createServerClient()
  const { data: contracts, error } = await supabase
    .from('contracts')
    .select(`*, occupants(*), audit_logs(*)`)
    .order('created_at', { ascending: false })

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  // Strip financial fields for staff role — enforced server-side
  const response = user.role === 'owner'
    ? contracts
    : contracts.map(c => stripFinancials(c))

  return NextResponse.json(response)
}

export async function POST(req: NextRequest) {
  const user = await getAuthUser(req)
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const supabase = createServerClient()
  const body = await req.json()
  const { occupants, ...contractData } = body

  // CF-XXXXXX numbering — use DB sequence via trigger, or fallback
  // Reference is auto-generated by DB trigger; if passed explicitly it's honoured
  const { data: contract, error } = await supabase
    .from('contracts')
    .insert({ ...contractData, stage: contractData.stage ?? 0 })
    .select()
    .single()

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })

  if (occupants?.length) {
    await supabase.from('occupants').insert(
      occupants.map((name: string) => ({ contract_id: contract.id, name }))
    )
  }

  await supabase.from('audit_logs').insert({
    contract_id: contract.id,
    actor: user.name,
    action: 'Contract created',
  })

  return NextResponse.json(contract, { status: 201 })
}
